version : '2'

services:
  twitter:
    build:
      context: ./data-producers
    container_name: twitter_01
    ports:
      - "9999:9999"
    volumes:
      - ./data-producers/Twitter:/home/ds
    command: jupyter-notebook --no-browser --port 9999 --ip='*' --allow-root
    depends_on:
      - manager

  iex:
    build:
      context: ./data-producers
    container_name: iex_01
    ports:
      - "8888:8888"
    volumes:
      - ./data-producers/IEX:/home/ds
    command: jupyter-notebook --no-browser --port 8888 --ip='*' --allow-root
    depends_on:
      - manager

  manager:
    build:
      context: ./data-producers
    container_name: manager_01
    ports:
      - "7777:7777"
    volumes:
      - ./data-producers/Manager:/home/ds
    command: jupyter-notebook --no-browser --port 7777 --ip='*' --allow-root
    depends_on:
      - data_store

  data_store:
    image: redis:alpine
