version : '2'


services:
    analytics:
      image: madderle/twitter-realtime-stocks:sklearn-model-deployment-1.0
      container_name: realtime_stock_model_deployment
      volumes:
        - ./src:/home/ds
      ports:
        - "7999:7999"
      command: python src/Daily_Model_Deployment.py
      environment:
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        - MONGODB_USER=${MONGO_INITDB_ROOT_USERNAME}
        - MONGODB_PASS=${MONGO_INITDB_ROOT_PASSWORD}
        - PYTHONUNBUFFERED=1
        - IP=${IP}
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PWD=${DB_PWD}
